test = {   'name': 'q4c',
    'points': 2,
    'suites': [   {   'cases': [   {'code': ">>> pump('zebra', 4) == 'zebrebrebrebra'\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> pump('hello', 1) == 'hello'\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> pump('sandiego', 15).count('andiega') == 7\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> pump('california', 5) == 'californialifornialifornialifornialifornia'\nTrue", 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
