test = {   'name': 'q1b',
    'points': None,
    'suites': [   {   'cases': [   {'code': '>>> isinstance(temp_probs, np.ndarray)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> np.isclose(temp_probs[0], 0.22)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> np.isclose(temp_probs[1], 0.25)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> np.isclose(temp_probs[2], 0.53)\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
