test = {   'name': 'q1e',
    'points': None,
    'suites': [   {   'cases': [   {'code': '>>> callable(airport_distance)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': ">>> np.isclose(airport_distance('SAN', 'DTW'), 1952.4829738365934)\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> np.isclose(airport_distance('LAX', 'SYD'), 7494.520943620303)\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> np.isclose(airport_distance('JFK', 'AMS'), 3633.5227886711236)\nTrue", 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
